# -*- coding: utf-8 -*-
"""資科導專題.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvZU_IolHSEFPezhRNKgrqeAP9DhMDgF
"""

import numpy as np
from datascience import *
import pandas as pd

pv= pd.read_csv('/content/drive/MyDrive/RESOURSE/104年內政大數據資料應用組競賽用資料集_村里.csv', low_memory=False)
pv



from google.colab import drive
drive.mount('/content/drive')